-- SUPERSEDIDA PELA 077. Nao aplicar.
--
-- Esta migration criava gold_review_queue_actionable_v3: o alvo do ML aplicado
-- na LISTA do cockpit. Funcionou (CUT_HOUR 81->32), mas era conserto de folha:
-- os CARDS do topo leem gold_action_impact_summary_v2, que pendura em
-- gold_recommendation_priority_v2 e nao passa pela lista. O dono viu na hora:
-- "as recomendacoes continuam as mesmas, o que mudou?".
--
-- A 077 corrige no envelope (priority_v2), de onde as QUATRO views herdam
-- (summary, actionable, review_queue, campaign_action_plan). A v3 virou
-- duplicidade — aplicava o mesmo override por cima, com uma fonte diferente de
-- "multiplicador atual" (divergiam em 7 linhas). Removida.
DROP VIEW IF EXISTS marketcloud_gold.gold_review_queue_actionable_v3;
